#!/usr/bin/env node
/**
 * Self-host the theme webfonts.
 *
 * For every font pair in src/libs/theme/fonts.ts this fetches the Google Fonts
 * CSS2 stylesheet, keeps the `latin` + `latin-ext` @font-face blocks (drops
 * cyrillic/greek/vietnamese to keep the payload small), downloads each woff2,
 * inlines it as a base64 data: URI, and writes a generated TS module:
 *
 *   src/libs/theme/generated/fontFaces.ts
 *     export const FONT_FACE_CSS: Record<string, string>   // keyed by fontKey
 *     export const DEFAULT_FONT_FACE_CSS: string           // inter-fraunces
 *
 * Re-run whenever fonts.ts changes. Output is committed (vendored asset).
 *
 *   node scripts/fetch-fonts.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const FONTS_TS = join(ROOT, 'src/libs/theme/fonts.ts');
const OUT_DIR = join(ROOT, 'src/libs/theme/generated');
const OUT_FILE = join(OUT_DIR, 'fontFaces.ts');

// Modern Chrome UA so Google serves woff2 (older UAs get ttf/eot).
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
const DEFAULT_KEY = 'inter-fraunces';

/** Pull `{ key: linkHref }` out of fonts.ts without importing TS. */
function parseFonts() {
  const src = readFileSync(FONTS_TS, 'utf8');
  // Match:  'key': { ... linkHref: '...' ... }  (linkHref may span lines)
  const entries = {};
  const blockRe = /'([a-z0-9-]+)':\s*\{([\s\S]*?)\n\s*\},/g;
  let m;
  while ((m = blockRe.exec(src)) !== null) {
    const key = m[1];
    const body = m[2];
    const href = body.match(/linkHref:\s*\n?\s*'([^']+)'/);
    if (href) entries[key] = href[1].replace(/&amp;/g, '&');
  }
  return entries;
}

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.text();
}

async function fetchWoff2DataUri(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  return `data:font/woff2;base64,${buf.toString('base64')}`;
}

/** Split the CSS2 response into { subset, block } using the `/* subset *\/` markers. */
function splitBlocks(css) {
  const out = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css)) !== null) out.push({ subset: m[1], block: m[2] });
  return out;
}

async function buildKey(key, href) {
  const css = await fetchText(href);
  const blocks = splitBlocks(css).filter((b) => KEEP_SUBSETS.has(b.subset));
  if (blocks.length === 0) throw new Error(`no latin blocks for ${key} (${href})`);

  // Cache woff2 downloads across blocks (same file can repeat).
  const cache = new Map();
  const rebuilt = [];
  for (const { block } of blocks) {
    const urlMatch = block.match(/src:\s*url\(([^)]+)\)/);
    if (!urlMatch) continue;
    const url = urlMatch[1].replace(/['"]/g, '');
    if (!cache.has(url)) cache.set(url, await fetchWoff2DataUri(url));
    const dataUri = cache.get(url);
    // Replace the remote url() with the data: URI; collapse whitespace.
    const inlined = block
      .replace(/src:\s*url\([^)]+\)/, `src: url(${dataUri})`)
      .replace(/\s+/g, ' ')
      .trim();
    rebuilt.push(inlined);
  }
  const bytes = rebuilt.join('').length;
  console.log(`  ${key}: ${blocks.length} faces, ~${Math.round(bytes / 1024)}KB`);
  return rebuilt.join('\n');
}

async function main() {
  const fonts = parseFonts();
  const keys = Object.keys(fonts);
  if (keys.length === 0) throw new Error('parsed 0 fonts from fonts.ts');
  console.log(`Fetching ${keys.length} font pairs (latin + latin-ext)…`);

  const map = {};
  for (const key of keys) {
    map[key] = await buildKey(key, fonts[key]);
  }
  if (!map[DEFAULT_KEY]) throw new Error(`default key ${DEFAULT_KEY} missing`);

  mkdirSync(OUT_DIR, { recursive: true });
  const body =
    '// AUTO-GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.\n' +
    '// Self-hosted webfonts (latin + latin-ext) as @font-face data: URIs.\n' +
    '// Re-run `node scripts/fetch-fonts.mjs` after changing fonts.ts.\n\n' +
    '/* eslint-disable */\n' +
    'export const FONT_FACE_CSS: Record<string, string> = {\n' +
    keys
      .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
      .join('\n') +
    '\n};\n\n' +
    `export const DEFAULT_FONT_FACE_CSS = FONT_FACE_CSS[${JSON.stringify(DEFAULT_KEY)}];\n`;

  writeFileSync(OUT_FILE, body);
  const totalKB = Math.round(body.length / 1024);
  console.log(`\nWrote ${OUT_FILE} (${totalKB}KB)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
